### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by yaazzz** [ppsx/cm3588-oled-screen#1]
Hi, are you sure about this? Can you give me the full copy command you use?

make copy of /boot/dtb-6.1.43-vendor-rk35xx/rockchip/overlay/rk3588-i2c8-m2.dtbo as /boot/dtb-6.1.43-vendor-rk35xx/rockchip/overlay/rockchip-rk3588-i2c 8-m2.dtbo to make it "visible" by the config

Which version of python are you using? I can not get pyproject.toml-based to be installed for the dependencies

**Comment by ppsx** [comment]
Armbian version I'm using:
v24.8.4 for FriendlyElec CM3588 NAS running Armbian Linux 6.1.75-vendor-rk35xx
Python 3.11.2
pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)

Things have changed since I was installing this (kernel, config, etc.).
I've updated readme. Please check again.
Regarding pyproject.toml - what's the exact issue you have?

**Comment by yaazzz** [comment]
Thanks for your reply. I get the following message when I try to install the requirements:

```
Failed to build evdev psutil spidev RPI.GPIO
ERROR: Could not build wheels for evdev, psutil, spidev, which is required to install pyproject.toml-based projects
```

**Comment by ppsx** [comment]
Please verify that you've got following packages installed:
libpython3-dev
libpython3.11-dev
python3-dev
python3-distutils
python3-setuptools
python3-venv
python3.11-dev
python3.11-venv

I'm not sure if anything else needed. Maybe these:
build-essential
make

**Comment by yaazzz** [comment]
Great! working well now. Moving to the next step ;) thanks again for your support

Can you config this pinout : GND to pin 6 - Vcc to pin 1 - SDA to pin 3 and SDL to pin 5 ? 

Self reply to myself yes it is the correct pin out  ;)
